[package]
name = "ruce_test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
core_simd = { git = "https://github.com/rust-lang/portable-simd" }
ruce_bindings = { git = "https://github.com/discordance/ruce"}